[package]
name = "shell"
version = "0.1.0"
authors = ["changex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc="3.1.7"
nix="0.20.0"
libc="0.2.68"